version: "3.8"

services:
  backend:
    build: ./backend
    container_name: php_backend
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: host.docker.internal  # Connect to local HeidiSQL DB
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: "Graduate Database"
    depends_on:
      - frontend # Keeps frontend as a service dependency (just for clarity, no effect)

  # frontend remains outside of Docker
  # No need to create a separate 'frontend' service here
