services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: grad_database
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

volumes:
  mysql_data: